# A-Sys-I HPC Profile Configuration
# High-Performance Computing environment using C++ shared memory bus.

mode: 'HPC'

# Output directory for captured data.
# This can be overridden by the ASYS_I_OUTPUT_DIR environment variable.
output_dir: './outputs/hpc_run'

bus:
  type: 'CppShardedSPMCBus'
  # Name for the message queue used for metadata transfer.
  # Should be unique on the system.
  meta_queue_name: 'asys_i_hpc_meta_queue'
  # Prefix for shared memory segments. All segments will be named <prefix>_<shard_id>.
  shm_name_prefix: 'asys_i_hpc_shm'
  num_shards: 4
  # Total size of shared memory in GB. This will be divided among shards.
  shared_memory_size_gb: 32 # This should match shm_size in docker-compose.yml
  spin_lock_timeout_us: 1000

hook:
  type: 'ActivationHooker'
  target_modules:
    - 'model.layers.0.mlp.gate_proj'
    - 'model.layers.1.mlp.gate_proj'
  # Size of pre-allocated pinned memory buffer in MB for async H2D copy.
  pinned_memory_buffer_size_mb: 1024

observer:
  type: 'HDF5Observer'
  # HDF5 file specific settings
  hdf5_chunk_size: 1024 # Number of activations per chunk
  hdf5_compression: 'gzip'
